### ISSUE TITLE
Can not find BaseModel.extendAndSetupCollection function

### ISSUE THREAD

**Issue by expandboard** [copleykj/socialize-base-model#14]
in your code you have written " Please use extendAndSetupCollection() to create your models ". but i can not find this class function so i encountered with Error when  run code. 
where can i find "BaseModel.extendAndSetupCollection" class?

**Comment by StorytellerCZ** [comment]
What version are you using?

**Comment by expandboard** [comment]
Hi Jan,
Base Model is v1.0.2 ,the current git in base model, and meteor is last version.

**Comment by copleykj** [comment]
extendAndSetupCollection doesn't exist in the new API and the error needs to be updated. You can either stick with an older version or you can follow the README and use the new API..

If you choose to stick with the new API you'll also want to downgrade to v1.0.1 as I've recently set newer versions unmigrated due to the breaking changes in `node-simpl-schema`
